// console.log(/a/.test("abd"));
// console.log(/\d/.test("1abd"));
// console.log(/\D/.test("1abd"));
// console.log(/\w/.test("qwe1_"));
// console.log(/\W/.test("qwe1_"));
// console.log(/\s/.test("qwe1_"));
// console.log(/\S/.test("\n"));
// console.log(/\S/.test("\r"));
// console.log(/\S/.test("\r\n"));
// console.log(/\S/.test("         "));
// console.log(/./.test("         "));
// console.log(/./.test(" "));
// console.log(/./.test("\r"));
// console.log(/./.test("\n"));
// console.log(/^a/.test("abjll"));
// console.log(/^a/.test("bjlal"));
// console.log(/d$/.test("bjlald"));
// console.log(/d$/.test("bjladl"));
// console.log(/^abcd$/.test("abcdabcd"));
// console.log(/^abcd/.test("aaabcdaa"));
console.log(/^abcd/.test("acbcdaa"));