// console.log(/^a*$/.test("aa"));
// console.log(/^a*$/.test(" bdsd"));
// console.log(/^a+$/.test("aaaa"));
// console.log(/^a+$/.test(""));
// console.log(/^a+$/.test("aa badsd"));
// console.log(/^a?$/.test("aa"));
// console.log(/^a?$/.test("a"));
// console.log(/^a?$/.test(""));
// console.log(/^a{2}$/.test("aaa"));
// console.log(/^a{2}$/.test("a"));
// console.log(/^a{2}$/.test("aa"));
// console.log(/^a{2,}$/.test("aa"));
// console.log(/^a{2,}$/.test("aaa"));
// console.log(/^a{2,}$/.test("a"));
// console.log(/^a{2,3}$/.test("a"));
// console.log(/^a{2,3}$/.test("aa"));
// console.log(/^a{2,3}$/.test("aaa"));
// console.log(/^[212swa]$/.test("aaa"));
// console.log(/^[212swa]$/.test("a"));
// console.log(/^[212swa]$/.test("3"));
// console.log(/^[212swa]$/.test("1"));
// console.log(/^[^21swa]$/.test("1"));
// console.log(/^[^21swa]$/.test("2"));
// console.log(/^[^21swa]$/.test("3"));
// console.log(/^[^21swa]$/.test("s"));
// console.log(/^[^21swa]$/.test("q"));
console.log(/^\.$/.test("."));